### ISSUE TITLE
Erro na importação QGIS

### ISSUE THREAD

**Issue by raulindo** [sgb-cprm/simbologia-mapeamento-geologico#1]
Fiz a importação da biblioteca de símbolos, mas os símbolos de mapeamento aparecem errados (Imagem Abaixo). 
Estou usando o  QGIS versão 3.18.2-Zürich. Não imagino o que pode ser, mas penso se não é alguma incompatibilidade de fonte (?). 

![import-mapeamento](https://user-images.githubusercontent.com/47931185/167667612-cb82c5d8-2084-4fb1-920f-0e98c2936207.PNG)

A importação dos símbolos de unidade de mapeamento deu certo.

**Comment by rodreras** [comment]
Você instalou as simbologias do arquivo .OTF no seu sistema?

**Comment by raulindo** [comment]
@rodreras não tinha me atentado a isso. Depois de seu comentário li toda a documentação na página e rolou! 
abs
